forward Models_OnGameModeInit();
public Models_OnGameModeInit()
{
    //SKINS
    //GUNS
    AddSimpleModel(-1, 347, -1000, "gun/taser.dff", "gun/taser.txd"); // TASER
    AddSimpleModel(-1, 352, -1001, "gun/glock18.dff", "gun/glock18.txd"); // GLOCK 18
    AddSimpleModel(-1, 347, -1002, "gun/glock17.dff", "gun/glock17.txd"); // GLOCK 17
    AddSimpleModel(-1, 347, -1003, "gun/glock19.dff", "gun/glock19.txd"); // GLOCK 19
    AddSimpleModel(-1, 347, -1004, "gun/870.dff", "gun/870.txd"); // REMINGTON 870
    AddSimpleModel(-1, 349, -1005, "gun/870.dff", "gun/870beanbag.txd"); //REMINGTON BEANBAG
    AddSimpleModel(-1, 358, -1006, "gun/scout.dff", "gun/scout.txd"); //STEYR SCOUT
    AddSimpleModel(-1, 353, -1007, "gun/hkmp5.dff", "gun/hkmp5.txd"); //HK MP5
    AddSimpleModel(-1, 356, -1008, "gun/hk416.dff", "gun/hk416.txd"); //HK 416
    AddSimpleModel(-1, 355, -1009, "gun/ak47.dff", "gun/ak47.txd"); //AK 47
    AddSimpleModel(-1, 372, -1010, "gun/tec9.dff", "gun/tec9.txd"); //ITec9
    AddSimpleModel(-1, 357, -1011, "gun/m16.dff", "gun/m16.txd"); //M16
    AddSimpleModel(-1, 348, -1012, "gun/detspl.dff", "gun/detspl.txd"); //Detective Special
    AddSimpleModel(-1, 348, -1013, "gun/1911.dff", "gun/1911.txd"); //1911
    AddSimpleModel(-1, 356, -1014, "gun/steyr-aug.dff", "gun/steyr-aug.txd"); //HK 416
    AddSimpleModel(-1, 355, -1015, "gun/kruger.dff", "gun/kruger.txd"); //Ruger
    AddSimpleModel(-1, 365, -1016, "gun/pepper.dff", "gun/pepper.txd"); //Gas Pimienta
    AddSimpleModel(-1, 365, -1017, "gun/spraycan.dff", "gun/spraycan.txd"); //Lata de spray
    AddSimpleModel(-1, 334, -1018, "gun/baton.dff", "gun/baton.txd"); //Baston policial

    AddCharModel(280, 20001, "skins/police/lapd1.dff", "skins/police/lapd1.txd");
    AddCharModel(267, 20002, "skins/police/hern.dff", "skins/police/hern.txd");
    AddCharModel(284, 20003, "skins/police/lapdm1.dff", "skins/police/lapdm1.txd");
    AddCharModel(266, 20004, "skins/police/pulaski.dff", "skins/police/pulaski.txd");
    AddCharModel(281, 20005, "skins/police/sfpd1.dff", "skins/police/sfpd1.txd");
    AddCharModel(265, 20006, "skins/police/tenpen.dff", "skins/police/tenpen.txd");
    AddCharModel(306, 20007, "skins/police/wfyclpd.dff", "skins/police/wfyclpd.txd");
    
    return 1;
}
