# .github/workflows/pawn-build.yml
name: Pawn Build
on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Try pawncc v3.10.11 (Linux x64 release)
        id: get-rel
        shell: bash
        run: |
          set -euo pipefail
          URL="https://github.com/openmultiplayer/compiler/releases/download/v3.10.11/pawnc-3.10.11-linux.tar.gz"
          echo "Downloading release: $URL"
          curl -fsSL "$URL" -o pawncc.tar.gz
          mkdir -p pawnc-bin
          tar -xzf pawncc.tar.gz -C pawnc-bin
          REL_DIR="pawnc-bin/pawnc-3.10.11-linux"
          chmod +x "$REL_DIR/bin/pawncc"
          export LD_LIBRARY_PATH="$PWD/$REL_DIR/lib"
          echo 'main(){}' > /tmp/_t.pwn
          set +e
          "$REL_DIR/bin/pawncc" /tmp/_t.pwn -o/dev/null
          rc=$?
          set -e
          if [ $rc -eq 0 ]; then
            echo "use_rel=$REL_DIR" >> $GITHUB_OUTPUT
          else
            echo "::warning::Release pawncc segfaulted or failed (rc=$rc), will build from source."
          fi

      - name: Build pawncc from source (fallback)
        if: ${{ steps.get-rel.outputs.use_rel == '' }}
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update && sudo apt-get install -y build-essential cmake git
          for REPO in openmultiplayer/compiler pawn-lang/compiler; do
            rm -rf pawnc-src || true
            git clone --depth=1 "https://github.com/$REPO.git" pawnc-src || continue
            if [ -f pawnc-src/source/compiler/CMakeLists.txt ]; then
              SRC="pawnc-src/source/compiler"
              break
            fi
          done
          [ -n "${SRC-}" ] || { echo "::error::No CMakeLists.txt in source/compiler"; exit 1; }
          cmake -S "$SRC" -B pawnc-src/build -DCMAKE_BUILD_TYPE=Release
          cmake --build pawnc-src/build -j
          echo "use_src=1" >> $GITHUB_OUTPUT

      - name: Validate layout
        shell: bash
        run: |
          test -f gamemodes/main.pwn || { echo "::error::missing gamemodes/main.pwn"; exit 1; }
          test -d qawno/include      || { echo "::error::missing qawno/include"; exit 1; }
          test -d gamemodes/modules  || { echo "::error::missing gamemodes/modules"; exit 1; }

      - name: Compile main.pwn (warnings fail, no artifact)
        shell: bash
        run: |
          set -o pipefail
          TARGET="gamemodes/main.pwn"

          if [ -n "${{ steps.get-rel.outputs.use_rel }}" ]; then
            PAWNCC="${{ steps.get-rel.outputs.use_rel }}/bin/pawncc"
            export LD_LIBRARY_PATH="$PWD/${{ steps.get-rel.outputs.use_rel }}/lib"
            echo "Using release pawncc: $PAWNCC"
          else
            PAWNCC="$PWD/pawnc-src/build/bin/pawncc"
            echo "Using source-built pawncc: $PAWNCC"
          fi

          "$PAWNCC" "$TARGET" \
            -iqawno/include \
            -igamemodes/modules \
            -d3 -Z+ -E -o/dev/null 2>&1 | tee build.log

          ec=${PIPESTATUS[0]}
          warns=$(grep -Eic 'warning[[:space:]]+[0-9]+:' build.log || true)
          echo "pawncc exit: $ec  warnings: $warns"
          if [ $ec -ne 0 ]; then echo "::error::pawncc exit $ec"; tail -n 200 build.log || true; exit $ec; fi
          if [ "$warns" -gt 0 ]; then echo "::error::Pawn warnings detected ($warns)"; grep -Ein 'warning[[:space:]]+[0-9]+:' build.log | tail -n 100 || true; exit 1; fi
          echo "OK: no warnings"