# .github/workflows/pawn-build.yml
name: Pawn Build

on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use repo compiler
        run: |
          chmod +x ./bin/pawncc
          echo "$PWD/bin" >> "$GITHUB_PATH"
          ls -l ./bin
          pawncc --version || true

      - name: Compile gamemode
        run: |
          pawncc gamemodes/main.pwn \
            -i include \
            -i qawno/include \
            -i gamemodes/modules \
            -d3 -Z+ -E -o /dev/null
