# .github/workflows/pawn-build.yml
name: Pawn Build

on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake git

      - name: Build pawncc from source
        run: |
          # Clone into a unique directory to avoid conflict with your repo's "compiler" folder
          git clone --depth=1 https://github.com/pawn-lang/compiler.git pawnc-src
          cmake -S pawnc-src -B pawnc-src/build -DCMAKE_BUILD_TYPE=Release
          cmake --build pawnc-src/build -j
          echo "$PWD/pawnc-src/build/bin" >> $GITHUB_PATH
          pawncc --version

      - name: Compile gamemode
        run: |
          pawncc gamemodes/main.pwn \
            -i include \
            -i qawno/include \
            -i gamemodes/modules \
            -d3 -Z+ -E -o /dev/null
