# .github/workflows/pawn-build.yml
name: Pawn Build
on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: ${{ github.workspace }}/bin
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Prep compiler
        shell: bash
        run: |
          ls -la bin
          chmod +x bin/pawncc
          file bin/pawncc
          file bin/libpawnc.so

      - name: Sanity check layout
        shell: bash
        run: |
          test -f gamemodes/main.pwn || { echo "::error::missing gamemodes/main.pwn"; exit 1; }
          for d in include qawno/include gamemodes gamemodes/modules; do
            [ -d "$d" ] || { echo "::error::missing $d"; exit 1; }
          done

      - name: Compile main.pwn (fail on warnings)
        shell: bash
        run: |
          set -o pipefail
          ./bin/pawncc gamemodes/main.pwn \
            -i include \
            -i qawno/include \
            -i gamemodes \
            -i gamemodes/modules \
            -d3 -E -o /dev/null 2>&1 | tee build.log
          ec=${PIPESTATUS[0]}
          if [ $ec -ne 0 ]; then
            echo "::error::pawncc exit $ec"; tail -n 200 build.log || true; exit $ec
          fi
          if grep -Eiq 'warning[[:space:]]+[0-9]+:' build.log; then
            echo "::error::Warnings detected"; grep -Ein 'warning[[:space:]]+[0-9]+:' build.log | tail -n 100; exit 1
          fi
          echo "OK: no warnings"