# .github/workflows/pawn-build.yml
name: Pawn Build
on:
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: ${{ github.workspace }}/bin
    steps:
      - uses: actions/checkout@v4

      - name: Use repo compiler
        run: |
          chmod +x ./bin/pawncc
          ls -l ./bin
          ./bin/pawncc

      - name: Compile gamemode
        run: |
          ./bin/pawncc gamemodes/main.pwn \
            -i include \
            -i qawno/include \
            -i gamemodes/modules \
            -d3 -Z+ -E -o /dev/null